# Generated by Django 4.2.1 on 2023-05-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='', verbose_name='picture')),
                ('desc', models.TextField()),
            ],
        ),
    ]
